# Generated by Django 4.2.5 on 2023-09-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='virtualalias',
            table='EmailApp_virtualalias',
        ),
    ]
